### ISSUE TITLE
Domain used to download libtool expired

### ISSUE THREAD

**Issue by yrougy** [ktemkin/gnuradio-for-mac-without-macports#67]
Hey there

Looks like the domain used to download libtool is a parked domain now (http://frgl.pw) so the download of libtool crashes (bad checksum, the content is html)

It's available in https://ftp.gnu.org/gnu/libtool/ though.

Thanks

**Comment by cfriedt** [comment]
Good catch. Can you make a PR?

**Comment by cfriedt** [comment]
If you are able to put together a fix yourself, can demonstrate that the fix works, and make a pull request, I will gladly merge your changes.

However, I no longer have access to a Mac OS machine, so cannot test changes individually. I'm also unable to build new releases unfortunately.

I'd be happy to merge PR's until the time someone else is able to take over maintainership.

**Comment by ktemkin** [comment]
Fixed in the gr3.8 branch. Closing.
