### ISSUE TITLE
Importing Additional Python Libraries

### ISSUE THREAD

**Issue by snow-hdgla** [ktemkin/gnuradio-for-mac-without-macports#89]
Hello! 

The instillation has so far worked great, thank you to those who support it!

I was wondering whether or not there would be a way to import additional python packages, say scipy for example, so that the package would be available for use within a python block in a gnuradio flowgraph?

Thanks for the insight!

**Comment by ktemkin** [comment]
Hi!

Any package installed using the Python.org python install should be usable from GNURadio -- you'll just need to install them using the `pip3` binary shipped with that distribution.

For example, to install a package called `foo`, you might use

```sh
$ /Library/Frameworks/Python.framework/Versions/3.7/bin/pip3 install foo
```

Let me know if you run into any difficulty. :)
